name: CI/CD

on:
    push:
        branches:
            - main
            - feat/pipable-stream
    pull_request:
        branches:
            - main
            - feat/pipable-stream

jobs:
    yarn:
        uses: ./.github/workflows/yarn-cache.yml

    test:
        needs: yarn
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - run: yarn test

    lint:
        needs: yarn
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - run: yarn lint

    build:
        needs: yarn
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - run: yarn prod:build
